#base constanst 
GLOBAL_INT=0
GLOBAL_FLOAT=1000
GLOBAL_CHAR=2000
GLOBAL_TEMP_INT=3000
GLOBAL_TEMP_FLOAT=4000
GLOBAL_TEMP_CHAR=5000
GLOBAL_TEMP_BOOL=6000

LOCAL_INT=7000
LOCAL_FLOAT=8000
LOCAL_CHAR=9000
LOCAL_TEMP_INT=10000
LOCAL_TEMP_FLOAT=11000
LOCAL_TEMP_CHAR=12000
LOCAL_TEMP_BOOL=13000

CONST_INT=14000
CONST_FLOAT=15000
CONST_CHAR=16000
CONST_STRING=17000

GLOBAL_TEMP_POINTER_INT=20000
GLOBAL_TEMP_POINTER_FLOAT=21000
GLOBAL_TEMP_POINTER_CHAR=22000

LOCAL_TEMP_POINTER_INT=23000
LOCAL_TEMP_POINTER_FLOAT=24000
LOCAL_TEMP_POINTER_CHAR=25000

#################################################################################      
#get memBase Value
memBase={
    'GLOBAL_INT'                : GLOBAL_INT,
    'GLOBAL_FLOAT'              : GLOBAL_FLOAT,
    'GLOBAL_CHAR'               : GLOBAL_CHAR,
    'GLOBAL_TEMP_INT'           : GLOBAL_TEMP_INT,
    'GLOBAL_TEMP_FLOAT'         : GLOBAL_TEMP_FLOAT,
    'GLOBAL_TEMP_CHAR'          : GLOBAL_TEMP_CHAR,
    'GLOBAL_TEMP_BOOL'          : GLOBAL_TEMP_BOOL,       
    'GLOBAL_TEMP_POINTER_INT'   : GLOBAL_TEMP_POINTER_INT,
    'GLOBAL_TEMP_POINTER_FLOAT' : GLOBAL_TEMP_POINTER_FLOAT,
    'GLOBAL_TEMP_POINTER_CHAR'  : GLOBAL_TEMP_POINTER_CHAR,
    'LOCAL_INT'                 : LOCAL_INT,
    'LOCAL_FLOAT'               : LOCAL_FLOAT,    
    'LOCAL_CHAR'                : LOCAL_CHAR,  
    'LOCAL_TEMP_INT'            : LOCAL_TEMP_INT,
    'LOCAL_TEMP_FLOAT'          : LOCAL_TEMP_FLOAT,
    'LOCAL_TEMP_CHAR'           : LOCAL_TEMP_CHAR,      
    'LOCAL_TEMP_BOOL'           : LOCAL_TEMP_BOOL,
    'LOCAL_TEMP_POINTER_INT'    : LOCAL_TEMP_POINTER_INT,
    'LOCAL_TEMP_POINTER_FLOAT'  : LOCAL_TEMP_POINTER_FLOAT,
    'LOCAL_TEMP_POINTER_CHAR'   : LOCAL_TEMP_POINTER_CHAR, 
    'CONST_INT'                 : CONST_INT,
    'CONST_FLOAT'               : CONST_FLOAT,
    'CONST_CHAR'                : CONST_CHAR,  
    'CONST_STRING'              : CONST_STRING
}

#################################################################################      
#get memBase
MEM =  {
    'GLOBAL': {
        'INT': 'GLOBAL_INT',
        'FLOAT': 'GLOBAL_FLOAT',
        'CHAR': 'GLOBAL_CHAR',
        'BOOl': 'GLOBAL_BOOL',
        'TEMP': {
            'INT': 'GLOBAL_TEMP_INT',
            'FLOAT': 'GLOBAL_TEMP_FLOAT',
            'CHAR': 'GLOBAL_TEMP_CHAR',
            'BOOL': 'GLOBAL_TEMP_BOOL',
            'POINTER': {
                'INT': 'GLOBAL_TEMP_POINTER_INT',
                'FLOAT': 'GLOBAL_TEMP_POINTER_FLOAT',
                'CHAR': 'GLOBAL_TEMP_POINTER_CHAR',
            }
        }
    },
    'LOCAL': {
        'INT': 'LOCAL_INT',
        'FLOAT': 'LOCAL_FLOAT',
        'CHAR': 'LOCAL_CHAR',
        'BOOL': 'LOCAL_BOOL',
        'TEMP': {
            'INT': 'LOCAL_TEMP_INT',
            'FLOAT': 'LOCAL_TEMP_FLOAT',
            'CHAR': 'LOCAL_TEMP_CHAR',
            'BOOL': 'LOCAL_TEMP_BOOL',
            'POINTER': {
                'INT': 'LOCAL_TEMP_POINTER_INT',
                'FLOAT': 'LOCAL_TEMP_POINTER_FLOAT',
                'CHAR': 'LOCAL_TEMP_POINTER_CHAR',
            }
        }
    }, 
    'CONST': {
        'INT': 'CONST_INT',
        'FLOAT': 'CONST_FLOAT',
        'CHAR': 'CONST_CHAR',
        'STRING': 'CONST_STRING'
    }
}

''' 
#ejercicioClase
GLOBAL_INT=5000
GLOBAL_FLOAT=8000
GLOBAL_CHAR=2000
GLOBAL_TEMPINT=3000
GLOBAL_TEMPFLOAT=4000
GLOBAL_TEMPCHAR=5000
GLOBAL_TEMPBOOL=6000
LOCAL_INT=11000
LOCAL_FLOAT=13000
LOCAL_CHAR=9000
LOCAL_TEMP_INT=15000
LOCAL_TEMPFLOAT=17000
LOCAL_TEMPCHAR=12000
LOCAL_TEMPBOOL=19000
CONST_INT=20000
CONST_FLOAT=205000
CONST_CHAR=16000
CONST_STRING=21000

'''